### ISSUE TITLE
Exceptions with Apache Maven 3.1.1

### ISSUE THREAD

**Issue by ehsavoie** [Commonjava/betterdep-maven-plugin#2]
Running the tree goals from the command line gives me the following exceptions : 
Exception in thread "main" java.lang.ClassCastException: org.slf4j.impl.SimpleLogger cannot be cast to org.slf4j.spi.LocationAwareLogger
        at org.commonjava.util.logging.ListenerSupport$LoggerListener.newMessages(ListenerSupport.java:183)
        at org.commonjava.util.logging.ListenerSupport$LogServer.run(ListenerSupport.java:157)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)
[Fatal Error] :48:33: L'entité "oslash" était référencée, mais pas déclarée.
[Fatal Error] :48:33: L'entité "oslash" était référencée, mais pas déclarée.
Exception in thread "Thread-4" java.lang.NoClassDefFoundError: org/neo4j/kernel/lifecycle/LifecycleException$1
        at org.neo4j.kernel.lifecycle.LifecycleException.humanReadableMessage(LifecycleException.java:34)
        at org.neo4j.kernel.lifecycle.LifecycleException.<init>(LifecycleException.java:66)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.stop(LifeSupport.java:515)
        at org.neo4j.kernel.lifecycle.LifeSupport.stop(LifeSupport.java:146)
        at org.neo4j.kernel.lifecycle.LifeSupport.shutdown(LifeSupport.java:178)
        at org.neo4j.kernel.InternalAbstractGraphDatabase.shutdown(InternalAbstractGraphDatabase.java:635)
        at org.commonjava.maven.atlas.graph.spi.neo4j.AbstractNeo4JEGraphDriver.close(AbstractNeo4JEGraphDriver.java:987)
        at org.commonjava.maven.atlas.graph.spi.neo4j.AbstractNeo4JEGraphDriver.run(AbstractNeo4JEGraphDriver.java:1002)
        at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.ClassNotFoundException: org.neo4j.kernel.lifecycle.LifecycleException$1
        at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:259)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:235)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:227)

While the first one may come from slf4j version incompatibility because I'm on 3.1.x instead of 3.0.x (which seems your maven-core version) the second is more disturbing.

**Comment by rnc** [comment]
Closing this as it no longer happens with current codebase.
